### ISSUE TITLE
can use Electron?

### ISSUE THREAD

**Issue by tomwey** [nomi-san/parsec-vdd#72]
I want using in Electron, can it supports?

**Comment by nomi-san** [comment]
What do you want? Integrate the core in your app?

**Comment by tomwey** [comment]
Currently, I am developing a windows program using the Electron framework. One of its functions is to create a virtual display. I wonder if it can be supported?

**Comment by nomi-san** [comment]
It's possible, there are two methods for you.

#### 1. Calling DLL with FFI

Include `parsec-vdd.h` in your C/C++ source and build as a DLL.
In JS side, use ffi-napi to call the exported functions from the DLL.

https://github.com/node-ffi-napi/node-ffi-napi
https://github.com/zhangyuang/node-ffi-rs

#### 2. Native node module

Like above, but the target is .node instead of DLL.
With NAPI wrapper, you can import this .node (using require) as normal Node.js module.

https://github.com/nodejs/node-addon-examples

The first method is easy to implement, the second requires more setup steps but it can be bundled into app.asar resources.

**Comment by tomwey** [comment]
ok, thx!
